{
 "title": "Experiment #1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "average_window",
    "query": "2s,5s,10s,20s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "network_device_name",
    "query": {
     "query": "node_network_transmit_bytes_total"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Broker Ingress",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total{topic=\"\"}[$average_window])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Broker Egress",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total{topic=\"\"}[$average_window])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ongoing Reassignment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_reassignmentbytesin_total[$average_window])"
    }
   ]
  },
  {
   "title": "Leader Count Per Broker",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network IO (Hardware)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"$network_device_name\"}[$average_window])",
     "legendFormat": "{{ instance }} transmitted"
    },
    {
     "expr": "-rate(node_network_receive_bytes_total{device=\"$network_device_name\"}[$average_window])",
     "legendFormat": "{{ instance }} received"
    }
   ]
  },
  {
   "title": "Leader Count Time Series",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}