package org.astraea.balancer.alpha.generator;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Supplier;
import java.util.stream.Collectors;
import org.astraea.balancer.alpha.ClusterLogAllocation;
import org.astraea.balancer.alpha.RebalancePlanGenerator;
import org.astraea.balancer.alpha.RebalancePlanProposal;
import org.astraea.cost.ClusterInfo;
import org.astraea.topic.TopicAdmin;

public class MonkeyPlanGenerator implements RebalancePlanGenerator<Void> {

  private final TopicAdmin topicAdmin;

  public MonkeyPlanGenerator(TopicAdmin topicAdmin) {
    this.topicAdmin = topicAdmin;
  }

  @Override
  public RebalancePlanProposal generate(ClusterInfo clusterNow, Void arguments) {

    // get current topic/partition/replica state
    final var listOfBrokers = List.copyOf(topicAdmin.brokerIds());
    final var replicas = topicAdmin.replicas(clusterNow.topics());

    // monkey pick a broker for you
    final var monkeyPickingBroker =
        (Supplier<Integer>)
            () -> listOfBrokers.get(ThreadLocalRandom.current().nextInt(0, listOfBrokers.size()));

    // proposal new plan
    final var afterRebalance =
        replicas.entrySet().stream()
            .collect(Collectors.groupingBy(x -> x.getKey().topic()))
            .entrySet()
            .stream()
            .map(
                x ->
                    Map.entry(
                        x.getKey(),
                        x.getValue().stream()
                            .collect(
                                Collectors.toUnmodifiableMap(
                                    y -> y.getKey().partition(),
                                    y ->
                                        y.getValue().stream()
                                            .map(replica -> monkeyPickingBroker.get())
                                            .collect(Collectors.toUnmodifiableList())))))
            .collect(Collectors.toUnmodifiableMap(Map.Entry::getKey, Map.Entry::getValue));

    System.out.println("After Rebalance");
    System.out.println(afterRebalance);

    // aggregate new result
    ClusterLogAllocation rebalancePlan = new ClusterLogAllocation(afterRebalance);
    return RebalancePlanProposal.builder()
        .withRebalancePlan(rebalancePlan)
        .withWarnings(List.of("This plan is generated by a monkey, use it at your own risk."))
        .build();
  }
}
